GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGVjMzEwM2EwNDFjMTYwMzRkN2QyYTIiLCJpYXQiOjE2MjYwOTE4MjAsImV4cCI6MTYyNjE3ODIyMH0.BpMiue3uaicf9N_Y1OxtEDHRYeNoIlF7f4cPl65S9k4

######
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "daviddeux@gmail.com",
    "password": "123456"
}
####
PUT  http://localhost:3000/api/sauces/60ec182da041c16034d7d292
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGUyZmU0ZDI5Y2U0YTBjNjBiNDY2ODAiLCJpYXQiOjE2MjYwNzg0OTUsImV4cCI6MTYyNjE2NDg5NX0.RJzRZRqECpeurQYSB-1TKu-PrcS4v_Nv_FOLLXLRF-k
Content-Type: application/json

{
  "name": "moutarde"
  
}


#####

DELETE  http://localhost:3000/api/sauces/60ebfc646bad972b44293598
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGUyZmU0ZDI5Y2U0YTBjNjBiNDY2ODAiLCJpYXQiOjE2MjYwNzg0OTUsImV4cCI6MTYyNjE2NDg5NX0.RJzRZRqECpeurQYSB-1TKu-PrcS4v_Nv_FOLLXLRF-k



######
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "davidcinq@gmail.com",
    "password": "123456"
}